services:
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    # volumes:
    #   - ./src:/var/www/html
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
    container_name: server
  php:
    build: 
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    # volumes:
    #   - ./src/:/var/www/html:delegated
    container_name: php
  mysql:
    image: mysql
    env_file:
      - ./env/mysql.env
    container_name: mysql
  composer:
    build:
      context: .
      dockerfile: ./dockerfiles/composer.dockerfile
    volumes:
      - ./src:/var/www/html
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    container_name: composer
  artisan: 
    build: 
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src/:/var/www/html
    container_name: artisan
    entrypoint: ["php", "/var/www/html/artisan"]
    depends_on:
      - mysql
  npm:
    image: node
    volumes:
      - ./src/:/var/www/html
    entrypoint: ["npm"]
    container_name: node
    working_dir: /var/www/html