services:
  mongodb:
    image: mongo
    container_name: goal-app-db
    env_file:
      - ./env/mongodb.env
    volumes:
      - mongodb:/app/db
  backend:
    build: ./backend
    container_name: goal-app-backend
    env_file:
      - ./env/backend.env
    ports:
      - 80:80
    volumes:
      - ./backend:/app:ro
      - backend-logs:/app/logs
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    container_name: goal-app-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src:ro
    depends_on:
      - backend

volumes:
  mongodb:
  backend-logs: